on:
  push:
    branches:
      - '*'

jobs:
  build:
    outputs:
      time: 
        description: 'The time we greeted you'
    runs:
      using: 'docker'
      image: 'wordpress/Dockerfile'
      args:
        - hello
    steps:
      - echo hellp